Output workflows

diff --git a/misc/action/fetch-workflows/action.yml b/misc/action/fetch-workflows/action.yml
--- a/misc/action/fetch-workflows/action.yml
+++ b/misc/action/fetch-workflows/action.yml
@@ -17,10 +17,16 @@ runs:
         for i in {1..60}
         do
           workflows=$(curl https://github.com/EnricoMi/publish-unit-test-result-action | grep "Used by" | sed -e "s/.*title=//" -e 's/[",]//g' | cut -d " " -f 1)
-          if [ "$workflows" -gt 0 ]; then break; fi
-          echo attempt $i failed
+          if [ "$workflows" -gt 0 ]
+          then
+            echo "total=$workflows" >> $GITHUB_OUTPUT
+            break
+          fi
+          echo "Attempt $i failed"
           sleep 60
         done
+        echo "Giving up"
+        exit 1
 
 branding:
   icon: 'download-cloud'
