Revert composite action

diff --git a/composite/action.yml b/composite/action.yml
--- a/composite/action.yml
+++ b/composite/action.yml
@@ -152,23 +152,117 @@ inputs:
 outputs:
   json:
     description: "Test results as JSON"
-    value: ${{ steps.run.outputs.json }}
+    value: ${{ steps.test-results.outputs.json }}
 
 runs:
   using: 'composite'
   steps:
-    - name: Check OS
+    - name: Check for Python3
+      id: python
       run: |
-        echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
-        cp -rv $GITHUB_ACTION_PATH/.. ./enricomi-publish-action-proxy
-        $GITHUB_ACTION_PATH/proxy.sh > ./enricomi-publish-action-proxy/action.yml
-        cat ./enricomi-publish-action-proxy/action.yml
+        echo '::group::Check for Python3'
+        # we check version here just to execute `python3` with an argument
+        # on Windows, there is a `python3.exe` that is a proxy to trigger installation from app store
+        # command `which python3` finds that, but `python3 -V` does not return the version on stdout
+        if ! which python3 || [[ "$(python3 -V)" != *"python 3."* && "$(python3 -V)" != *"Python 3."* ]]
+        then
+          if ! which python || [[ "$(python -V)" != *"python 3."* && "$(python -V)" != *"Python 3."* ]]
+          then
+            echo "::error::No python3 interpreter found. Please setup python before running this action. You could use https://github.com/actions/setup-python."
+            exit 1
+          fi
+
+          PYTHON_BIN="$(python -c 'import sys; print(sys.executable)')"
+        else
+          PYTHON_BIN="$(python3 -c 'import sys; print(sys.executable)')"
+        fi
+
+        echo "Python that creates venv: $PYTHON_BIN"
+        echo "PYTHON_BIN=$PYTHON_BIN" >> "$GITHUB_ENV"
+        echo "version=$("$PYTHON_BIN" -V)" >> "$GITHUB_OUTPUT"
+        echo '::endgroup::'
       shell: bash
 
-    - name: Run
-      id: run
-      uses: ./enricomi-publish-action-proxy
+    - name: Detect OS
+      id: os
+      run: |
+        case "$RUNNER_OS" in
+          Linux*)
+            echo "pip-cache=~/.cache/pip" >> "$GITHUB_OUTPUT"
+            ;;
+          macOS*)
+            echo "pip-cache=~/Library/Caches/pip" >> "$GITHUB_OUTPUT"
+            ;;
+          Windows*)
+            echo "pip-cache=~\\AppData\\Local\\pip\\Cache" >> "$GITHUB_OUTPUT"
+            echo "pip-options=--user" >> "$GITHUB_OUTPUT"
+            ;;
+        esac
+      shell: bash
+
+    - name: Restore PIP packages cache
+      uses: actions/cache/restore@v4
+      id: cache
+      continue-on-error: true
       with:
+        path: ${{ steps.os.outputs.pip-cache }}
+        key: enricomi-publish-action-${{ runner.os }}-${{ runner.arch }}-pip-${{ steps.python.outputs.version }}-70a313922fdbeb7398ec60313d908b11
+
+    - name: Create virtualenv
+      id: venv
+      continue-on-error: true
+      env:
+        PIP_OPTIONS: ${{ steps.os.outputs.pip-options }}
+      run: |
+        echo '::group::Create virtualenv'
+        echo "Python that creates venv: $PYTHON_BIN"
+
+        echo "Creating virtual environment"
+        if ! "$PYTHON_BIN" -m virtualenv enricomi-publish-action-venv && ! "$PYTHON_BIN" -m venv enricomi-publish-action-venv
+        then
+          echo "Looks like there is neither virtualenv nor venv package installed"
+          if ! "$PYTHON_BIN" -m pip install $PIP_OPTIONS virtualenv && [ -n "$PIP_OPTIONS" ]
+          then
+            echo "Installing virtualenv package with PIP options '$PIP_OPTIONS' failed, now trying without"
+            "$PYTHON_BIN" -m pip install virtualenv
+          fi
+
+          if ! "$PYTHON_BIN" -m virtualenv enricomi-publish-action-venv
+          then
+            echo "Still cannot create venv after installing virtualenv package"
+            exit 1
+          fi
+        fi
+
+        echo "Finding Python interpreter in venv"
+        case "$RUNNER_OS" in
+          Linux*|macOS*)
+            PYTHON_VENV="enricomi-publish-action-venv/bin/python";;
+          Windows*)
+            PYTHON_VENV="enricomi-publish-action-venv\\Scripts\\python";;
+        esac
+        PYTHON_VENV="$("$PYTHON_VENV" -c 'import sys; print(sys.executable)')"
+        echo "Python in venv: $PYTHON_VENV"
+        echo "PYTHON_VENV=$PYTHON_VENV" >> "$GITHUB_ENV"
+        echo '::endgroup::'
+      shell: bash
+
+    - name: Install Python dependencies
+      run: |
+        echo '::group::Install Python dependencies'
+        # make sure wheel is installed, which improves installing our dependencies
+        "$PYTHON_VENV" -m pip install wheel
+        "$PYTHON_VENV" -m pip install -r "$GITHUB_ACTION_PATH/../python/requirements.txt"
+        echo '::endgroup::'
+      shell: bash
+
+    - name: Publish Test Results
+      id: test-results
+      run: |
+        echo '::group::Publish Test Results'
+        "$PYTHON_VENV" "$GITHUB_ACTION_PATH/../python/publish_test_results.py"
+        echo '::endgroup::'
+      env:
         GITHUB_TOKEN: ${{ inputs.github_token }}
         GITHUB_TOKEN_ACTOR: ${{ inputs.github_token_actor }}
         GITHUB_RETRIES: ${{ inputs.github_retries }}
@@ -210,11 +304,15 @@ runs:
         SEARCH_PULL_REQUESTS: ${{ inputs.search_pull_requests }}
         ROOT_LOG_LEVEL: ${{ inputs.root_log_level }}
         LOG_LEVEL: ${{ inputs.log_level }}
-
-    - name: Clean up
-      if: always()
-      run: rm -rf ./enricomi-publish-action-proxy
       shell: bash
+
+    - name: Save PIP packages cache
+      uses: actions/cache/save@v4
+      if: ( success() || failure() ) && ! steps.cache.outputs.cache-hit
+      continue-on-error: true
+      with:
+        path: ${{ steps.os.outputs.pip-cache }}
+        key: ${{ steps.cache.outputs.cache-primary-key }}
 
 branding:
   icon: 'check-circle'
