Isolate pip cache used by composite action

diff --git a/composite/action.yml b/composite/action.yml
--- a/composite/action.yml
+++ b/composite/action.yml
@@ -150,6 +150,10 @@ inputs:
     description: 'Prior to v2.6.0, the action used the "/search/issues" REST API to find pull requests related to a commit. If you need to restore that behaviour, set this to "true". Defaults to "false".'
     default: 'false'
     required: false
+  pip_cache_path:
+    description: 'Path to a PIP cache exclusively used by this action.'
+    default: ''
+    required: false
 
 outputs:
   json:
@@ -207,15 +211,16 @@ runs:
       id: os
       run: |
         # Detect OS
+        default_path="${{ inputs.pip_cache_path }}"
         case "$RUNNER_OS" in
           Linux*)
-            echo "pip-cache=~/.cache/pip" >> "$GITHUB_OUTPUT"
+            echo "pip-cache=${default_path:-~/.cache/pip-enricomi-publish-action}" >> "$GITHUB_OUTPUT"
             ;;
           macOS*)
-            echo "pip-cache=~/Library/Caches/pip" >> "$GITHUB_OUTPUT"
+            echo "pip-cache=${default_path:-~/Library/Caches/pip-enricomi-publish-action}" >> "$GITHUB_OUTPUT"
             ;;
           Windows*)
-            echo "pip-cache=~\\AppData\\Local\\pip\\Cache" >> "$GITHUB_OUTPUT"
+            echo "pip-cache=${default_path:-~\\AppData\\Local\\pip\\Cache-enricomi-publish-action}" >> "$GITHUB_OUTPUT"
             echo "pip-options=--user" >> "$GITHUB_OUTPUT"
             ;;
         esac
@@ -227,7 +232,7 @@ runs:
       continue-on-error: true
       with:
         path: ${{ steps.os.outputs.pip-cache }}
-        key: enricomi-publish-action-${{ runner.os }}-${{ runner.arch }}-pip-${{ steps.python.outputs.version }}-b0048519e3287ae9cfc634aeda40cbfe
+        key: enricomi-publish-action-pip-${{ runner.os }}-${{ runner.arch }}-${{ steps.python.outputs.version }}-b0048519e3287ae9cfc634aeda40cbfe
 
     - name: Create virtualenv
       id: venv
@@ -244,10 +249,10 @@ runs:
         if ! "$PYTHON_BIN" -m virtualenv enricomi-publish-action-venv && ! "$PYTHON_BIN" -m venv enricomi-publish-action-venv
         then
           echo "Looks like there is neither virtualenv nor venv package installed"
-          if ! "$PYTHON_BIN" -m pip install $PIP_OPTIONS virtualenv && [ -n "$PIP_OPTIONS" ]
+          if ! "$PYTHON_BIN" -m pip --cache-dir "${{ steps.os.outputs.pip-cache }}" install $PIP_OPTIONS virtualenv && [ -n "$PIP_OPTIONS" ]
           then
             echo "Installing virtualenv package with PIP options '$PIP_OPTIONS' failed, now trying without"
-            if ! "$PYTHON_BIN" -m pip install virtualenv
+            if ! "$PYTHON_BIN" -m pip --cache-dir "${{ steps.os.outputs.pip-cache }}" install virtualenv
             then
               echo "::error::Installing virtualenv package failed"
               exit 1
@@ -279,7 +284,7 @@ runs:
       run: |
         # Install Python dependencies
         echo '::group::Install Python dependencies'
-        "$PYTHON_VENV" -m pip install -r "$GITHUB_ACTION_PATH/../python/requirements-$DEPENDENCIES_VERSION.txt"
+        "$PYTHON_VENV" -m pip --cache-dir "${{ steps.os.outputs.pip-cache }}" install -r "$GITHUB_ACTION_PATH/../python/requirements-$DEPENDENCIES_VERSION.txt"
         echo '::endgroup::'
       shell: bash
 
@@ -344,6 +349,19 @@ runs:
       with:
         path: ${{ steps.os.outputs.pip-cache }}
         key: ${{ steps.cache.outputs.cache-primary-key }}
+
+    - name: Clean up
+      if: always()
+      continue-on-error: true
+      run: |
+        # Clean up
+        echo '::group::Clean up'
+        find "${{ steps.os.outputs.pip-cache }}"
+        rm -rf "enricomi-publish-action-venv"
+        rm -rfv "${{ steps.os.outputs.pip-cache }}"
+        find "${{ steps.os.outputs.pip-cache }}"
+        echo '::endgroup::'
+      shell: bash
 
 branding:
   icon: 'check-circle'
diff --git a/windows/bash/action.yml b/windows/bash/action.yml
--- a/windows/bash/action.yml
+++ b/windows/bash/action.yml
@@ -150,6 +150,10 @@ inputs:
     description: 'Prior to v2.6.0, the action used the "/search/issues" REST API to find pull requests related to a commit. If you need to restore that behaviour, set this to "true". Defaults to "false".'
     default: 'false'
     required: false
+  pip_cache_path:
+    description: 'Path to a PIP cache exclusively used by this action.'
+    default: '~\AppData\Local\pip\Cache-enricomi-publish-action'
+    required: false
 
 outputs:
   json:
@@ -202,8 +206,8 @@ runs:
       id: cache
       continue-on-error: true
       with:
-        path: '~\AppData\Local\pip\Cache'
-        key: enricomi-publish-action-${{ runner.os }}-${{ runner.arch }}-pip-${{ steps.python.outputs.version }}-b0048519e3287ae9cfc634aeda40cbfe
+        path: ${{ inputs.pip_cache_path }}
+        key: enricomi-publish-action-pip-${{ runner.os }}-${{ runner.arch }}-${{ steps.python.outputs.version }}-b0048519e3287ae9cfc634aeda40cbfe
 
     - name: Create virtualenv
       id: venv
@@ -218,10 +222,10 @@ runs:
         if ! "$PYTHON_BIN" -m virtualenv enricomi-publish-action-venv && ! "$PYTHON_BIN" -m venv enricomi-publish-action-venv
         then
           echo "Looks like there is neither virtualenv nor venv package installed"
-          if ! "$PYTHON_BIN" -m pip install --user virtualenv
+          if ! "$PYTHON_BIN" -m pip --cache-dir "${{ inputs.pip_cache_path }}" install --user virtualenv
           then
             echo "Installing virtualenv package with PIP options '--user' failed, now trying without"
-            if ! "$PYTHON_BIN" -m pip install virtualenv
+            if ! "$PYTHON_BIN" -m pip --cache-dir "${{ inputs.pip_cache_path }}" install virtualenv
             then
               echo "::error::Installing virtualenv package failed"
               exit 1
@@ -248,7 +252,7 @@ runs:
       run: |
         # Install Python dependencies
         echo '::group::Install Python dependencies'
-        "$PYTHON_VENV" -m pip install -r "$GITHUB_ACTION_PATH/../../python/requirements-$DEPENDENCIES_VERSION.txt"
+        "$PYTHON_VENV" -m pip --cache-dir "${{ inputs.pip_cache_path }}" install -r "$GITHUB_ACTION_PATH/../../python/requirements-$DEPENDENCIES_VERSION.txt"
         echo '::endgroup::'
       shell: bash
 
@@ -311,8 +315,21 @@ runs:
       if: ( success() || failure() ) && ! steps.cache.outputs.cache-hit
       continue-on-error: true
       with:
-        path: '~\AppData\Local\pip\Cache'
+        path: ${{ inputs.pip_cache_path }}
         key: ${{ steps.cache.outputs.cache-primary-key }}
+
+    - name: Clean up
+      if: always()
+      continue-on-error: true
+      run: |
+        # Clean up
+        echo '::group::Clean up'
+        find "${{ inputs.pip_cache_path }}"
+        rm -rf enricomi-publish-action-venv
+        rm -rfv "${{ inputs.pip_cache_path }}"
+        find "${{ inputs.pip_cache_path }}"
+        echo '::endgroup::'
+      shell: bash
 
 branding:
   icon: 'check-circle'
