OS-specific composite actions (#576)

diff --git a/composite/action.yml b/composite/action.yml
--- a/composite/action.yml
+++ b/composite/action.yml
@@ -42,7 +42,7 @@ inputs:
     default: 'false'
     required: false
   files:
-    description: 'File patterns of test result files. Relative paths are known to work best, while the composite action also works with absolute paths. Supports "*", "**", "?", and "[]" character ranges. Use multiline string for multiple patterns. Patterns starting with "!" exclude the matching files. There have to be at least one pattern starting without a "!".'
+    description: 'File patterns of test result files. Relative paths are known to work best, while the non-Docker action also works with absolute paths. Supports "*", "**", "?", and "[]" character ranges. Use multiline string for multiple patterns. Patterns starting with "!" exclude the matching files. There have to be at least one pattern starting without a "!".'
     required: false
   junit_files:
     description: 'Deprecated, use "files" option instead.'
@@ -151,10 +151,18 @@ outputs:
 runs:
   using: 'composite'
   steps:
+    - name: Deprecation warning
+      run: |
+        # Print deprecation warning
+        echo "::warning::Running this action via 'uses: EnricoMi/publish-unit-test-result-action/composite@v2 is deprecated! For details, see: https://github.com/EnricoMi/publish-unit-test-result-action/tree/v2#running-as-a-composite-action"
+      shell: bash
+
     - name: Check for Python3
       id: python
       run: |
+        # Check for Python3
         echo '::group::Check for Python3'
+
         # we check version here just to execute `python3` with an argument
         # on Windows, there is a `python3.exe` that is a proxy to trigger installation from app store
         # command `which python3` finds that, but `python3 -V` does not return the version on stdout
@@ -174,12 +182,14 @@ runs:
         echo "Python that creates venv: $PYTHON_BIN"
         echo "PYTHON_BIN=$PYTHON_BIN" >> "$GITHUB_ENV"
         echo "version=$("$PYTHON_BIN" -V)" >> "$GITHUB_OUTPUT"
+
         echo '::endgroup::'
       shell: bash
 
     - name: Detect OS
       id: os
       run: |
+        # Detect OS
         case "$RUNNER_OS" in
           Linux*)
             echo "pip-cache=~/.cache/pip" >> "$GITHUB_OUTPUT"
@@ -208,7 +218,9 @@ runs:
       env:
         PIP_OPTIONS: ${{ steps.os.outputs.pip-options }}
       run: |
+        # Create virtualenv
         echo '::group::Create virtualenv'
+
         echo "Python that creates venv: $PYTHON_BIN"
 
         echo "Creating virtual environment"
@@ -218,12 +230,16 @@ runs:
           if ! "$PYTHON_BIN" -m pip install $PIP_OPTIONS virtualenv && [ -n "$PIP_OPTIONS" ]
           then
             echo "Installing virtualenv package with PIP options '$PIP_OPTIONS' failed, now trying without"
-            "$PYTHON_BIN" -m pip install virtualenv
+            if ! "$PYTHON_BIN" -m pip install virtualenv
+            then
+              echo "::error::Installing virtualenv package failed"
+              exit 1
+            fi
           fi
 
           if ! "$PYTHON_BIN" -m virtualenv enricomi-publish-action-venv
           then
-            echo "Still cannot create venv after installing virtualenv package"
+            echo "::error::Cannot create venv after installing virtualenv package"
             exit 1
           fi
         fi
@@ -238,21 +254,26 @@ runs:
         PYTHON_VENV="$("$PYTHON_VENV" -c 'import sys; print(sys.executable)')"
         echo "Python in venv: $PYTHON_VENV"
         echo "PYTHON_VENV=$PYTHON_VENV" >> "$GITHUB_ENV"
+
         echo '::endgroup::'
       shell: bash
 
     - name: Install Python dependencies
       run: |
+        # Install Python dependencies
         echo '::group::Install Python dependencies'
+
         # make sure wheel is installed, which improves installing our dependencies
         "$PYTHON_VENV" -m pip install wheel
         "$PYTHON_VENV" -m pip install -r "$GITHUB_ACTION_PATH/../python/requirements.txt"
+
         echo '::endgroup::'
       shell: bash
 
     - name: Publish Test Results
       id: test-results
       run: |
+        # Publish Test Results
         echo '::group::Publish Test Results'
         "$PYTHON_VENV" "$GITHUB_ACTION_PATH/../python/publish_test_results.py"
         echo '::endgroup::'
diff --git a/windows/bash/action.yml b/windows/bash/action.yml
--- a/windows/bash/action.yml
+++ b/windows/bash/action.yml
@@ -146,10 +146,159 @@ inputs:
 outputs:
   json:
     description: "Test results as JSON"
+    value: ${{ steps.test-results.outputs.json }}
 
 runs:
-  using: 'docker'
-  image: 'docker://ghcr.io/enricomi/publish-unit-test-result-action:v2.14.0'
+  using: 'composite'
+  steps:
+    - name: Check for Python3
+      id: python
+      run: |
+        # Check for Python3
+        echo '::group::Check for Python3'
+
+        # we check version here just to execute `python3` with an argument
+        # on Windows, there is a `python3.exe` that is a proxy to trigger installation from app store
+        # command `which python3` finds that, but `python3 -V` does not return the version on stdout
+        if ! which python3 || [[ "$(python3 -V)" != *"python 3."* && "$(python3 -V)" != *"Python 3."* ]]
+        then
+          if ! which python || [[ "$(python -V)" != *"python 3."* && "$(python -V)" != *"Python 3."* ]]
+          then
+            echo "::error::No python3 interpreter found. Please setup python before running this action. You could use https://github.com/actions/setup-python."
+            exit 1
+          fi
+
+          PYTHON_BIN="$(python -c 'import sys; print(sys.executable)')"
+        else
+          PYTHON_BIN="$(python3 -c 'import sys; print(sys.executable)')"
+        fi
+
+        echo "Python that creates venv: $PYTHON_BIN"
+        echo "PYTHON_BIN=$PYTHON_BIN" >> "$GITHUB_ENV"
+        echo "version=$("$PYTHON_BIN" -V)" >> "$GITHUB_OUTPUT"
+
+        echo '::endgroup::'
+      shell: bash
+
+    - name: Restore PIP packages cache
+      uses: actions/cache/restore@v4
+      id: cache
+      continue-on-error: true
+      with:
+        path: '~\AppData\Local\pip\Cache'
+        key: enricomi-publish-action-${{ runner.os }}-${{ runner.arch }}-pip-${{ steps.python.outputs.version }}-70a313922fdbeb7398ec60313d908b11
+
+    - name: Create virtualenv
+      id: venv
+      continue-on-error: true
+      run: |
+        # Create virtualenv
+        echo '::group::Create virtualenv'
+
+        echo "Python that creates venv: $PYTHON_BIN"
+
+        echo "Creating virtual environment"
+        if ! "$PYTHON_BIN" -m virtualenv enricomi-publish-action-venv && ! "$PYTHON_BIN" -m venv enricomi-publish-action-venv
+        then
+          echo "Looks like there is neither virtualenv nor venv package installed"
+          if ! "$PYTHON_BIN" -m pip install --user virtualenv
+          then
+            echo "Installing virtualenv package with PIP options '--user' failed, now trying without"
+            if ! "$PYTHON_BIN" -m pip install virtualenv
+            then
+              echo "::error::Installing virtualenv package failed"
+              exit 1
+            fi
+          fi
+
+          if ! "$PYTHON_BIN" -m virtualenv enricomi-publish-action-venv
+          then
+            echo "::error::Cannot create venv after installing virtualenv package"
+            exit 1
+          fi
+        fi
+
+        echo "Finding Python interpreter in venv"
+        PYTHON_VENV="enricomi-publish-action-venv\\Scripts\\python"
+        PYTHON_VENV="$("$PYTHON_VENV" -c 'import sys; print(sys.executable)')"
+        echo "Python in venv: $PYTHON_VENV"
+        echo "PYTHON_VENV=$PYTHON_VENV" >> "$GITHUB_ENV"
+
+        echo '::endgroup::'
+      shell: bash
+
+    - name: Install Python dependencies
+      run: |
+        # Install Python dependencies
+        echo '::group::Install Python dependencies'
+
+        # make sure wheel is installed, which improves installing our dependencies
+        "$PYTHON_VENV" -m pip install wheel
+        "$PYTHON_VENV" -m pip install -r "$GITHUB_ACTION_PATH/../../python/requirements.txt"
+
+        echo '::endgroup::'
+      shell: bash
+
+    - name: Publish Test Results
+      id: test-results
+      run: |
+        # Publish Test Results
+        echo '::group::Publish Test Results'
+        "$PYTHON_VENV" "$GITHUB_ACTION_PATH/../../python/publish_test_results.py"
+        echo '::endgroup::'
+      env:
+        GITHUB_TOKEN: ${{ inputs.github_token }}
+        GITHUB_TOKEN_ACTOR: ${{ inputs.github_token_actor }}
+        GITHUB_RETRIES: ${{ inputs.github_retries }}
+        COMMIT: ${{ inputs.commit }}
+        CHECK_NAME: ${{ inputs.check_name }}
+        COMMENT_TITLE: ${{ inputs.comment_title }}
+        COMMENT_MODE: ${{ inputs.comment_mode }}
+        FAIL_ON: ${{ inputs.fail_on }}
+        ACTION_FAIL: ${{ inputs.action_fail }}
+        ACTION_FAIL_ON_INCONCLUSIVE: ${{ inputs.action_fail_on_inconclusive }}
+        FILES: ${{ inputs.files }}
+        JUNIT_FILES: ${{ inputs.junit_files }}
+        NUNIT_FILES: ${{ inputs.nunit_files }}
+        XUNIT_FILES: ${{ inputs.xunit_files }}
+        TRX_FILES: ${{ inputs.trx_files }}
+        TIME_UNIT: ${{ inputs.time_unit }}
+        TEST_FILE_PREFIX: ${{ inputs.test_file_prefix }}
+        REPORT_INDIVIDUAL_RUNS: ${{ inputs.report_individual_runs }}
+        REPORT_SUITE_LOGS: ${{ inputs.report_suite_logs }}
+        DEDUPLICATE_CLASSES_BY_FILE_NAME: ${{ inputs.deduplicate_classes_by_file_name }}
+        LARGE_FILES: ${{ inputs.large_files }}
+        IGNORE_RUNS: ${{ inputs.ignore_runs }}
+        COMPARE_TO_EARLIER_COMMIT: ${{ inputs.compare_to_earlier_commit }}
+        PULL_REQUEST_BUILD: ${{ inputs.pull_request_build }}
+        EVENT_FILE: ${{ inputs.event_file }}
+        EVENT_NAME: ${{ inputs.event_name }}
+        TEST_CHANGES_LIMIT: ${{ inputs.test_changes_limit }}
+        CHECK_RUN_ANNOTATIONS: ${{ inputs.check_run_annotations }}
+        CHECK_RUN_ANNOTATIONS_BRANCH: ${{ inputs.check_run_annotations_branch }}
+        SECONDS_BETWEEN_GITHUB_READS: ${{ inputs.seconds_between_github_reads }}
+        SECONDS_BETWEEN_GITHUB_WRITES: ${{ inputs.seconds_between_github_writes }}
+        SECONDARY_RATE_LIMIT_WAIT_SECONDS: ${{ inputs.secondary_rate_limit_wait_seconds }}
+        JSON_FILE: ${{ inputs.json_file }}
+        JSON_THOUSANDS_SEPARATOR: ${{ inputs.json_thousands_separator }}
+        JSON_SUITE_DETAILS: ${{ inputs.json_suite_details }}
+        JSON_TEST_CASE_RESULTS: ${{ inputs.json_test_case_results }}
+        CHECK_RUN: ${{ inputs.check_run }}
+        JOB_SUMMARY: ${{ inputs.job_summary }}
+        SEARCH_PULL_REQUESTS: ${{ inputs.search_pull_requests }}
+        # not documented
+        ROOT_LOG_LEVEL: ${{ inputs.root_log_level }}
+        # not documented
+        LOG_LEVEL: ${{ inputs.log_level }}
+      shell: bash
+
+    - name: Save PIP packages cache
+      uses: actions/cache/save@v4
+      if: ( success() || failure() ) && ! steps.cache.outputs.cache-hit
+      continue-on-error: true
+      with:
+        path: '~\AppData\Local\pip\Cache'
+        key: ${{ steps.cache.outputs.cache-primary-key }}
 
 branding:
   icon: 'check-circle'
