Add python_interpreter input to composite action

diff --git a/composite/action.yml b/composite/action.yml
--- a/composite/action.yml
+++ b/composite/action.yml
@@ -142,6 +142,9 @@ inputs:
     description: 'Prior to v2.6.0, the action used the "/search/issues" REST API to find pull requests related to a commit. If you need to restore that behaviour, set this to "true". Defaults to "false".'
     default: 'false'
     required: false
+  python_interpreter:
+    description: 'Path of the Python interpreter to use for this action. This can point into a virtual environment (recommended). A single package will be installed into that Python environment if it does not yet exist: virtualenv.'
+    required: false
 
 outputs:
   json:
@@ -155,26 +158,31 @@ runs:
       id: python
       run: |
         echo '##[group]Check for Python3'
-        # we check version here just to execute `python3` with an argument
-        # on Windows, there is a `python3.exe` that is a proxy to trigger installation from app store
-        # command `which python3` finds that, but `python3 -V` does not return the version on stdout
-        if ! which python3 || [[ $(python3 -V) != *"python 3."* && $(python3 -V) != *"Python 3."* ]]
+        if [ -n "${{ inputs.python_interpreter }}" ]
         then
-          if ! which python || [[ $(python -V) != *"python 3."* && $(python -V) != *"Python 3."* ]]
+          echo "PYTHON=${{ inputs.python_interpreter }}" >> $GITHUB_ENV
+          echo "version=$(${{ inputs.python_interpreter }} -V)" >> $GITHUB_OUTPUT
+          which "${{ inputs.python_interpreter }}"
+        else
+          # we check version here just to execute `python3` with an argument
+          # on Windows, there is a `python3.exe` that is a proxy to trigger installation from app store
+          # command `which python3` finds that, but `python3 -V` does not return the version on stdout
+          if ! which python3 || [[ $(python3 -V) != *"python 3."* && $(python3 -V) != *"Python 3."* ]]
           then
-            echo "::error::No python3 interpreter found. Please setup python before running this action. You could use https://github.com/actions/setup-python."
-            exit 1
-          fi
-
-          interpreter="$(which python)"
-          if [[ ! -e "${interpreter}3" ]]
-          then
-            mkdir -p "$RUNNER_TEMP/bin/"
-            ln -s "$interpreter" "$RUNNER_TEMP/bin/python3"
-            echo "$RUNNER_TEMP/bin" >> $GITHUB_PATH
+            if ! which python || [[ $(python -V) != *"python 3."* && $(python -V) != *"Python 3."* ]]
+            then
+              echo "::error::No python3 interpreter found. Please setup python before running this action. You could use https://github.com/actions/setup-python."
+              exit 1
+            fi
+            echo "PYTHON=$(which python)" >> $GITHUB_ENV
+            echo "version=$(python -V)" >> $GITHUB_OUTPUT
+            which python
+          else
+            echo "PYTHON=$(which python3)" >> $GITHUB_ENV
+            echo "version=$(python3 -V)" >> $GITHUB_OUTPUT
+            which python3
           fi
         fi
-        echo "version=$(python3 -V)" >> $GITHUB_OUTPUT
         echo '##[endgroup]'
       shell: bash
 
@@ -211,8 +219,8 @@ runs:
       run: |
         echo '##[group]Create virtualenv'
         # install virtualenv, if it is not yet installed
-        python3 -m pip install $PIP_OPTIONS virtualenv
-        python3 -m virtualenv enricomi-publish-action-venv
+        ${PYTHON} -m pip install $PIP_OPTIONS virtualenv
+        ${PYTHON} -m virtualenv enricomi-publish-action-venv
         # test activating virtualenv
         case "$RUNNER_OS" in
           Linux*|macOS*)
